# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  database: listings_development
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  database: listings_production
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  database: listings_test
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432
